POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "Great Scott!",
  "postType": "post",
  "slug": "great-scott",
  "status": "draft",
  "content": "This is some content.",
  "schema": "{\"@context\": \"https:\/\/schema.org\", \"@type\": \"Person\"}",
  "featuredImageUrl": "https://outtatime.com/images/doc.png",
  "publishOn": "2026-02-04T08:00:00-06:00",
  "tags": [ "time-travel", "delorean" ],
  "metaOptions": [
    {
      "key": "isPost",
      "value": true
    }
  ]
}